### ISSUE TITLE
Make it easier to load existing PDF documents into the ViewPrinter

### ISSUE THREAD

**Issue by EarlyWild** [natario1/ViewPrinter#15]
Add the ability to display existing PDF documents. As far as I can see, there is no easy way of doing this. If there is, please share!

**Comment by EarlyWild** [comment]
Just to make it clear, it is easy to render a single page PDF document, but I do know how to render multi-page PDF documents.

**Comment by natario1** [comment]
Well this is a PDF creator, not a renderer... we rely on external apps to show the PDF result, see the demo app.

If you want to display PDF embedded in your app, I think there are libraries that do this pretty well.
